# These are supported funding model platforms

github: LANNOVA
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://mempool.space/address/bc1q5kmqqynratseyh7v0n8q58rn7p5xejuemmc4px', 'https://etherscan.io/address/0x8558288490E11E7F900471E7D52F0b0A0B6b8572']
